# Generated by Django 5.1.7 on 2025-04-10 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anestesicos',
            fields=[
                ('idanestesico', models.AutoField(db_column='idAnestesico', primary_key=True, serialize=False)),
                ('nombreanestesico', models.CharField(db_column='NombreAnestesico', max_length=45)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Anestésico',
                'verbose_name_plural': 'Anestésicos',
                'db_table': 'anestesicos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('idbitacora', models.AutoField(db_column='idBitacora', primary_key=True, serialize=False)),
                ('fechacirujia', models.DateField(db_column='FechaCirujia')),
                ('dosis', models.FloatField(blank=True, db_column='Dosis', null=True)),
                ('dosistotal', models.FloatField(blank=True, db_column='DosisTotal', null=True)),
                ('pesoexperimento', models.FloatField(blank=True, db_column='PesoExperimento', null=True)),
                ('actividad', models.IntegerField(blank=True, db_column='Actividad', null=True)),
                ('archivos', models.CharField(blank=True, db_column='Archivos', max_length=45, null=True)),
                ('ubicacionarchivo', models.CharField(db_column='UbicacionArchivo', max_length=45)),
                ('notas', models.CharField(blank=True, db_column='Notas', max_length=45, null=True)),
            ],
            options={
                'verbose_name': 'Bitácora',
                'verbose_name_plural': 'Bitácoras',
                'db_table': 'bitacora',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cajas',
            fields=[
                ('idcaja', models.AutoField(db_column='idCaja', primary_key=True, serialize=False)),
                ('cantidadratas', models.IntegerField(db_column='CantidadRatas')),
                ('sexo', models.CharField(db_column='Sexo', max_length=45)),
                ('fechanacimiento', models.DateField(db_column='FechaNacimiento')),
                ('comentarios', models.CharField(db_column='Comentarios', max_length=45)),
                ('talla', models.CharField(db_column='Talla', max_length=45)),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'db_table': 'cajas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Condiciones',
            fields=[
                ('idcondicion', models.AutoField(db_column='idCondicion', primary_key=True, serialize=False)),
                ('nombrecondicion', models.CharField(db_column='NombreCondicion', max_length=45)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=250)),
            ],
            options={
                'verbose_name': 'Condición',
                'verbose_name_plural': 'Condiciones',
                'db_table': 'condiciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('idrol', models.AutoField(db_column='idRol', primary_key=True, serialize=False)),
                ('nombrerol', models.CharField(db_column='NombreRol', max_length=45)),
                ('descripcion', models.CharField(db_column='Descripción', max_length=45)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tejidos',
            fields=[
                ('idtejido', models.AutoField(db_column='idTejido', primary_key=True, serialize=False)),
                ('nombretejido', models.CharField(db_column='NombreTejido', max_length=45)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=45)),
            ],
            options={
                'verbose_name': 'Tejido',
                'verbose_name_plural': 'Tejidos',
                'db_table': 'tejidos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('idusuario', models.AutoField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('nombreusuario', models.CharField(db_column='NombreUsuario', max_length=45)),
                ('apellidopaterno', models.CharField(db_column='ApellidoPaterno', max_length=45)),
                ('apellidomaterno', models.CharField(db_column='ApellidoMaterno', max_length=45)),
                ('sexo', models.CharField(db_column='Sexo', max_length=45)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ratas',
            fields=[
                ('idrata', models.OneToOneField(db_column='idRata', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventario.bitacora')),
                ('fechacirugia', models.DateField(db_column='FechaCirugia')),
                ('pesosemanal', models.FloatField(db_column='PesoSemanal')),
                ('numerocola', models.IntegerField(db_column='NumeroCola')),
            ],
            options={
                'verbose_name': 'Rata',
                'verbose_name_plural': 'Ratas',
                'db_table': 'ratas',
                'managed': False,
            },
        ),
    ]
