# Generated by Django 5.2 on 2025-04-29 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={'managed': False, 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
